services:
  db:
    image: postgres:15-alpine
    container_name: spending_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expense-network

  backend:
    build: ./backend
    container_name: fastapi_app
    environment:
      - ENABLE_AI=false
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://user:password@db:5432/dbname 
    deploy:
      resources:
        limits:
          memory: 4G 
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./backend/models:/code/models 
    env_file:
      - ./backend/.env
    # Dùng sh -c để chạy nhiều lệnh
    command: >
      sh -c "python /code/download_model.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    networks:
      - expense-network

  frontend:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      # Sửa cổng thành 8000 để khớp với backend bên trên
      - NEXT_PUBLIC_API_URL=http://localhost:8000

    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      
    networks:
      - expense-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  expense-network:
    driver: bridge